name: CI workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve code
        uses: actions/checkout@v3
      - name: Install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install depedencies
        run: npm ci
      - name: Run tests
        run: npm test

  deploy:
    needs: test # specify order. An array can be used if multiple jobs need to be successfull first
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve code
        uses: actions/checkout@v3
      - name: Install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install depedencies
        run: npm ci
      - name: Build project
        run: npm run build
