name: CI workflow

on:
  push:
    branches:
      - main
# can take an array if multiple events trigger are required
# activity types and event filters can be added to be more specific about the event
# if mulitple events but one doesnt have types and filters, colon are still required

# ACTIVITY TYPES
# on:
#   pull_request:
#     types: [opened, edited]
#   workflow_dispatch:

# FILTERS
# on:
#   pull_request:
#     types: [opened, edited]
#   workflow_dispatch:
#   push:
#     branches:
#       - main
#       - 'dev-*' -> branches starting with dev
#       - 'feature/**' -> allow more slashes
#     paths: -> if a push include changes in a specific path
#     paths-ignore:
#       - '.github/workflows/*'

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context
        run: echo "${{ toJson(github) }}"
        # context: various metadata about the workflow and actions.
        # will print Object if toJson is not called

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve code
        uses: actions/checkout@v3

      - name: Install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs: # JOB OUTPUT
      script-file: ${{ steps.publish.outputs.script-file }} # steps.<id>.outputs.variableName. variableName has to match the one below
    steps:
      - name: Retrieve code
        uses: actions/checkout@v3

      - name: Install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish JS filename # JOB OUTPUT STEP
        id: publish # required
        run: find dist/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';' # <- this one

      - name: Upload build
        uses: actions/upload-artifact@v3 # UPLOAD ARTIFACT
        with:
          name: dist-files
          path: |
            dist
            public

  deploy-to-stage:
    needs: build # specify order. can take an array if multiple jobs need to be successfull first
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve code
        uses: actions/checkout@v3

      - name: Install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install depedencies
        run: npm ci

      - name: Downloading dependencies
        uses: actions/download-artifact@v3 # DOWNLOAD ARTIFACT
        with:
          name: dist-files

      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file }}" # this script-file correspond to the key script file in the build job

      - name: Staging project
        run: echo "deploying..."
